name: Lint And Test
on:
  pull_request:
    types: [opened, edited]
    branches:
      - "*"

jobs:
  lint-and-test:
    uses: otedesco/gh-action-templates/.github/workflows/lint-and-test.yml@main
    secrets: inherit
