name: Release

on:
  push:
    branches:
      - develop
      - stage
  workflow_dispatch:

jobs:
  lint-and-test:
    uses: otedesco/gh-action-templates/.github/workflows/lint-and-test.yml@main
    secrets: inherit

  release:
    needs: [lint-and-test]
    uses: otedesco/gh-action-templates/.github/workflows/release-docker.yml@main
    secrets: inherit
